# ipad2-unlock Containerized

:toc:

== Introduction ==
** This is the software using the libimobiledevice - ideviceactivation to activate an icloud locked ipad2.
This works in windows and linux, but this code is mainly for a linux debian slim container. I did try alpine and ubuntu, but some of the apt installs / apk installs did not work. 
Am attempting to run it in Fedora 40 workstation at present.

NOTE: I got it to work using podman container, using a localized script that I copy to do the task.
After the local script is copied, it runs the required apt installs, goes into the libimobiledevice git repo, compiles the executables, and then runs it, to unlock the ipad device, if connected.
it also uses the ldconfig, which is in the script inst_icu.sh file, to address errors when running ideviceactivation, after initial installation. This is probably because of configuration files not in the right path.

**Instructions**

Install apt and 
download inst_icu.sh and unicloud.sh and chmod 777 both these files; Also download the Dockerfile (obviously!)
Then run

  $podman build -t icloud-unlock:unlock .


== finds
 
found out only lately that using the local /var/run works, because it uses the usbmuxd service locally from the host. Now have found a way to use usbmuxd from within the container, using usbmuxd -v or -s in a tmux session. but if ipad is reconnected, it requires usbmuxd to be restarted. trying to find a way to make ipad redectable. tried to map /dev/bus/usb, but ipad uses a different bus after reconnecting.{creation of container is $podman run -it -v /var/run:/var/run --entrypoint=/bin/bash icloud-unlock:latest}

to try using this, as bash script is not running inside the dockerfile during build of the podman container
ENTRYPOINT /my-script.sh ; /my-script2.sh ; /bin/bash

try the following ref - https://stackoverflow.com/questions/31578446/running-a-script-inside-a-docker-container-using-shell-script



NOTE: usbmuxd uses TCP port 27015

==addendum
 following are just excerpts for reference. ignore for now.
.
.
.
.
.

run $podman run -it --privileged -v /dev/bus/usb/001:/dev/bus/usb/001 --net=host 55b4bde1184c
use for reference - docker run -it -v /var/run:/var/run --entrypoint=/bin/bash debian:unstable-slim
they key here is /var/run:/var/run, as anything else, even /dev/bus/usb does not work not even /var. I think the /var/run has the required libraries associated with the ipad device to connect to the container properly. I need to figure this out.
NOTE: tried to get it working in an Acer Chromebook R16 I think, but it did not work, even after ensuring that the ipad device is allocated to the linux subsystem
NOTE: If running the unlock script over internet, using a vodafone network, it will be blocked by vodafone

NOTE: to use the sliver.php and the celeanger server app

reference old one = $podman run -it --privileged -v /dev/bus/usb/001:/dev/bus/usb/001 --net=host 55b4bde1184c
reference website, but for idevicerestore = https://github.com/lukepasek/idevicerestore
